#!/bin/bash

set -e

display_usage() {
	echo "Auto configuration for systemd-named-netns."
	echo -e "\nUsage:\n\t$0 network-type ns-name config-file\n"
	echo "Note: you may need root privileges for this."
}

autoconfigure_interface() {
	if [ ! -z "$MACADDR" ]; then
		/bin/ip link set ${DEVNAME_INSIDE} address ${MACADDR}
	fi
	if [ "${DHCPV4}" == "1" ]; then
		dhclient -v -i ${DEVNAME_INSIDE} -nw -pf /var/run/dhclient-${NSNAME}_${DEVNAME_INSIDE}.pid
	else
		if [ ! -z "${IPADDR_V4}" ]; then
			/bin/ip address add ${IPADDR_V4} dev ${DEVNAME_INSIDE}
		fi
		if [ ! -z "${GATEWAY_V4}" ]; then
			/bin/ip route add default via ${GATEWAY_V4}
		fi
		if [ ! -z "${IPADDR_V6}" ]; then
			/bin/ip -6 address add ${IPADDR_V6} dev ${DEVNAME_INSIDE}
		fi
		if [ ! -z "${GATEWAY_V6}" ]; then
			/bin/ip -6 route add default via ${GATEWAY_V6}
		fi
	fi
	return 0 # additional precation against "set -e" in case of future mods of this function
}

autoconfigure() {
	local NSTYPE=$1
	local NSNAME=$2
	local DEVNAME_INSIDE=$3
	local CONFIG=$4

	echo "Starting autoconfigure for $NSTYPE ${NSNAME}"

	source "${CONFIG}"

	if type -t autoconfigure_$NSTYPE >/dev/null ; then
		autoconfigure_$NSTYPE "$@"
	fi

	echo "Autoconfiguration finished."
}

if [ $# == 0 ]; then
	display_usage
	exit 1
fi

case "$1" in
	"--help" | "-h")
		display_usage
		exit 0
		;;
	"interface"|"bridge")
		autoconfigure "$@"
		exit 0
		;;
	*)
		echo "Unknown network type. Quitting."
		exit 1
		;;
esac
