name: Debian Package Build

on:
  release:
    types:
      - published

env:
  DEBIAN_FRONTEND: noninteractive
  DEBEMAIL: packaging@wand.net.nz
  DEBFULLNAME: WAND Packaging

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y upgrade
          apt-get -y install devscripts dpkg-dev debhelper equivs
      - name: Bump version
        run: |
          debchange --newversion ${{ github.event.release.tag_name }} -b "New upstream release"
      - name: Build package
        run: |
          mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
          dpkg-buildpackage -b -us -uc -rfakeroot
          package_path="${GITHUB_WORKSPACE}/packages/any-distro_any-version"
          mkdir -p "${package_path}"
          mv ../*.deb "${package_path}"
      - name: Publish packages to cloudsmith
        uses: wanduow/action-cloudsmith-upload-packages@v1
        with:
          path: packages/
          repo: wand/systemd-named-netns
          username: brad-cowie
          api_key: ${{ secrets.CLOUDSMITH_API_KEY }}
